---
abstract: 'Translate text from one language to another'
author:
  - 'Marcel Gruenauer <marcel@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.11
generated_by: 'Dist::Zilla version 1.100711'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Text-Pipe-Translate
provides:
  Text::Pipe::Translate:
    file: lib/Text/Pipe/Translate.pm
    version: 1.100890
  Text::Pipe::Translate::Babelfish:
    file: lib/Text/Pipe/Translate/Babelfish.pm
    version: 1.100890
requires:
  Carp: 0
  English: 0
  File::Find: 0
  File::Temp: 0
  LWP::UserAgent: 0
  Lingua::Translate: 0
  Scalar::Util: 0
  Test::More: 0.88
  Text::Pipe: 0
  Text::Pipe::Base: 0
  constant: 0
  parent: 0
  perl: 5.008
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Text-Pipe-Translate
  homepage: http://search.cpan.org/dist/Text-Pipe-Translate/
  repository: http://github.com/hanekomu/Text-Pipe-Translate
version: 1.100890
