---
abstract: 'Translate text from one language to another'
author:
  - 'Marcel GrE<uuml>nauer, C<< <marcel@cpan.org> >>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.70
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Text-Pipe-Translate
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  LWP::UserAgent: 0
  Lingua::Translate: 0
  Text::Pipe: 0.03
  perl: 5.6.0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Text-Pipe-Translate
  homepage: http://search.cpan.org/dist/Text-Pipe-Translate/
  license: http://dev.perl.org/licenses/
  repository: git://github.com/hanekomu/text-pipe-translate.git
version: 0.04
